package ai.rever.boss.plugin.dynamic.playground

import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow

/**
 * In-memory ring buffer of the last [MAX] calls made through the playground.
 *
 * Session-only by design - the playground is a development aid and persistence
 * across launches would be more confusing than useful (tool sets change every
 * launch). Order is most-recent-first; [MAX] is the size of the buffer, not a
 * minimum.
 */
class CallHistory {
    private val _records = MutableStateFlow<List<CallRecord>>(emptyList())
    val records: StateFlow<List<CallRecord>> = _records.asStateFlow()

    /**
     * Record one call. [CallRecord.id] is generated by the caller so retries of
     * the same call are distinguishable in the list.
     */
    fun add(record: CallRecord) {
        val current = _records.value
        val updated = (listOf(record) + current).take(MAX)
        _records.value = updated
    }

    fun clear() {
        _records.value = emptyList()
    }

    companion object {
        const val MAX: Int = 20
    }
}

/**
 * One MCP tool invocation through the playground.
 *
 * @param id unique per call (timestamp-based is enough - session only).
 * @param toolName tool name as registered (e.g. `git_status`).
 * @param providerId owning provider id, used for grouping in the panel.
 * @param argsJson the JSON arguments string the operator submitted verbatim.
 * @param resultText the [ai.rever.boss.plugin.api.McpToolResult.text] on success.
 * @param isError true if the handler returned isError=true OR the call threw.
 * @param errorMessage present when the call threw before reaching a result.
 * @param durationMs wall-clock duration of the call, including the throw path.
 * @param timestamp epoch ms at which the call was issued.
 */
data class CallRecord(
    val id: Long,
    val toolName: String,
    val providerId: String,
    val argsJson: String,
    val resultText: String?,
    val isError: Boolean,
    val errorMessage: String?,
    val durationMs: Long,
    val timestamp: Long,
)
